### PR TITLE
Version 10.4

### PR DESCRIPTION
**Pull request by adamfain**
- print button on history (order details) screen will be visible if the
  order type exists in 'CanPrintOrderType' option's csv list

### CODE REVIEW

**Comment by adamfain** [comment]
Hi Rory,

please do not merge this branch yet. I just noticed that Order Date shows wrong.

screenshot 87

**Comment by adamfain** [comment]
Hi Rory,

all done. Please see attached screenshot.

screenshot 88

**Comment by roryenslin** [comment]
Thanks Adam
I will do

On Thu, Feb 25, 2016 at 11:52 AM, Adam Fain notifications@github.com
wrote:

> Hi Rory,
> 
> all done. Please see attached screenshot.
> 
> [image: screenshot 88]
> https://cloud.githubusercontent.com/assets/15938467/13315906/c71adc58-dbad-11e5-9b24-57d1d185eb63.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rapidtrade/RapidJQ/pull/4#issuecomment-188696710.

## 

Regards
Rory Enslin

Tel 011 493 9755
Cell 082 454 0749
Email  rory@rapidtrade.biz
Help desk  help@rapidtrade.biz

Kindly email all your new support related queries to help@rapidtrade.biz as
our personal e-mail addresses are not always monitored and could result in
a delayed response. The above email address is always monitored and your
email would be attended to as per our SLA.

Please keep in mind our SLA
1. High Priority relates to order and pricing issue's (solved within 6 hours
)
2. Medium Priority relates to synchronisation issue's (solved within 24
hours)
3. Low Priority relates to all other issues (solved within 3 days)

**Comment by roryenslin** [comment]
Closing

**Pull request merged**
